version = 1

[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
  dialect = "typescript"
  environment = ["browser", "nodejs"]
  style_guide = "standard"

[[transformers]]
name = "prettier"
enabled = true

exclude_patterns = [
  "node_modules/**",
  "dist/**",
  "build/**",
  "coverage/**",
  "src/data/mock*/**"
]
