version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  # ✅ Enable TypeScript and React analysis
  runtime = "node"
  dialect = "typescript"
  modules = ["react"]

[[transformers]]
name = "prettier"
enabled = true

# 🧠 Ignore build, node_modules, and mock data folders
exclude_patterns = [
  "node_modules/**",
  "build/**",
  "dist/**",
  "coverage/**",
  "src/data/mock*/**"
]
