name: Deploy Supabase Edge Functions
on:
  push:
    branches: [ "Sportime-stable-oct17" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy api-football-proxy
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy api-football-proxy --project-ref "${{ secrets.SUPABASE_PROJECT_REF }}"
